### ISSUE TITLE
Custom Radio Station plays music only

### ISSUE THREAD

**Issue by zenius11** [rumangerst/CSLMusicMod#9] opened 2016-12-19 08:16 UTC
Hello. Whenever I run CSLMusicMod, my custom radio station only plays music. No ads nor blurb will play. The funny thing is, it worked last night. I didn't change the code at all from last night, I didn't remove any of the relevant audio files, the JSON is valid and the blurb and adverts play normally on VLC! When I click on an ad/blurb, it just skips to music! What's happened?

Code:
`
> {
>  "name": "RadioEDM",
>  "collections": [
>    "EDM"
>  ],
>  "thumbnail": "img.png",
>  "schedule": [
>    {
>      "type": "music",
>      "min": 1,
>      "max": 3
>   },
>    {
>      "type": "blurb",
>      "min": 1,
>      "max": 1
>    },
>    {
>      "type": "commercial",
>      "min": 1,
>      "max": 2
>    },
>	{
>      "type": "blurb",
>      "min": 1,
>      "max": 1
>    }
>  ]
>}
`

**Comment by rumangerst** [comment] 2016-12-19 08:47
Hi,
I have a hypothesis what could be the cause of this, but I don't know if it's correct. Can you tell me:

* What OS you are using
* The full paths (C:\Program Files\...\music file.ogg) to some of the non-working files
* The Cities: Skylines log where you failed to try to play them (Just upload them somewhere - no need to clean something up; github gist, ...)

**Comment by zenius11** [comment] 2016-12-19 12:34
OS: Windows 10
Path: C:\Program Files (x86)\Steam\SteamApps\common\Cities_Skylines\CSLMusicMod_Music\EDM\ (All files are placed here
Log: http://bead.tk/B0nD4

**Comment by rumangerst** [comment] 2016-12-19 17:01
Should be fixed with version 1.1.3.2. Caused by the really annoying system Unity uses for loading stuff. They expect you to provide an URI, but never explain how to do it correctly. Even the Cities: Skylines developers seem to do it wrong and it only works because they don't have any special characters in their filenames.

**Closed** 2016-12-23 08:26 UTC
